services:
  mongodb:
    image: mongo:6.0
    restart: always
    container_name: mongodb-6.0
    ports:
      - 26017:27017
    volumes:
      -  ~/apps/mongo:/data/db
      - ./mongo-init/init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
