spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: courtaution
      connection-string: mongodb://localhost:27017/courtaution
